Algoritmo "Par_ou_Impar"


Var

   N1, N2: Inteiro
   
   
Inicio

     EscrevaL("Digite um número para descobrimos se é impar ou par!")
       Leia(N1)
     Escreval("---------------")
    Se (N1 Mod 2 = 0) entao
     Escreval(N1, " Par!")
    Senao
     Escreval(N1, " Ímpar!")

    Fimse
    
      Escreval("Digite um número para verificar se é par ou impar!")
       leia(N2)
      Escreval("--------------")

    Se (N2 Mod 2 = 0) entao
      Escreval(N2, " Par!")
    Senao
      Escreval(N2, " Ímpar!")

     Fimse
    
Fimalgoritmo