Algoritmo "Vetor"



Var

    Notas: Vetor[1..5] De real
    
      
Inicio

    Notas[1] <- 8.0      //guarda 8.0 na primeira posição
    Notas[2] <- 6.0     //guarda 6.0 na segunda posição
    Notas[3] <- 7.0    //guarda 7.0 na terceira posição
    Notas[4] <- 5.0   //guarda 5.0 na quarta posição
    Notas[5] <- 3.0  //guarda 3.0 na quinta posição


Escreval(" A nota é de: ", Notas[5])

Fimalgoritmo