Algoritmo "Operacao_Com_Dois_Numeros"


Var

  N1, N2, Soma, Divisao, Multiplicacao, subtracao: Real
  
  
Inicio

   Escreval("Digite um número!")
   leia(N1)
   Escreval("Digite um segundo número!")
   leia(N2)
   
   Soma <- N1 + N2
   Divisao <- N1 / N2
   Multiplicacao <- N1 * N2
   Subtracao <- N1 - N2
   
   EscrevaL("A soma de dois número é: ", Soma)
   Escreval("A divisão do primeiro pelo segundo é: ", Divisao)
   Escreval("A multiplicação de dois número é: ", Multiplicacao)
   Escreval("A subtração do primeiro pelo segundo é: ", Subtracao)
   
   
Fimalgoritmo